### ISSUE TITLE
为什么有时候无法显示中奖名单

### ISSUE THREAD

**Issue by xiaoyangh** [huyinghuan/lottery-2016#1]
按回车弹了一个wow之后就停止了，没有显示中奖名单，有时候

**Comment by huyinghuan** [comment]
没有中奖名单可能是服务器没反应
![image](https://cloud.githubusercontent.com/assets/3005433/20374871/4e05d3a6-acb6-11e6-9ed1-bff26e77225d.png)

**Comment by xiaoyangh** [comment]
那应该怎么解决呢？有时候是有的，有时候又没有

**Comment by huyinghuan** [comment]
可以自己找到文件

`lottery-2016/static/lottery-start.js` 的 106行到150行进行断点debug。
本人测试多次均未重现你说的 问题
![image](https://cloud.githubusercontent.com/assets/3005433/20374956/db902c1c-acb6-11e6-94a2-e41cc4a65a59.png)

**Comment by xiaoyangh** [comment]
![c3631344-4a1b-4f9b-ac1c-efb0633b47c6](https://cloud.githubusercontent.com/assets/1456254/20375149/362c7b84-acb8-11e6-93ec-ebee5a5fd9d7.png)
刚刚调试了，貌似关闭掉wow之后就没有往下走了

**Comment by huyinghuan** [comment]
关掉后执行了
![image](https://cloud.githubusercontent.com/assets/3005433/20375222/c5ce1018-acb8-11e6-89ef-3b5bbabaff61.png)

请逐步断点 看下到哪一边出错了

**Comment by huyinghuan** [comment]
问题可能出在这几行
![image](https://cloud.githubusercontent.com/assets/3005433/20375276/2205a328-acb9-11e6-9133-24dae8f4da8d.png)
看看html是否填充进去了，或者是否找到相对应的dom元素，  抑或在 console控制台看下报错信息

**Comment by xiaoyangh** [comment]
厉害！，果然是这里报错了
lottery-start.js:36 Uncaught TypeError: Cannot read property 'id' of undefined(…)(anonymous function) @ lottery-start.js:36
lottery-start.js:36 Uncaught TypeError: Cannot read property 'id' of undefined(…)(anonymous function) @ lottery-start.js:36
handlebars.js:3234 Uncaught Exceptiondescription: undefinedfileName: undefinedlineNumber: undefinedmessage: "You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined"name: "Error"number: undefinedstack: "Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined↵    at Object.compile (http://localhost:3000/lib/handlebars.js:3234:12)↵    at HandlebarsEnvironment.hb.compile (http://localhost:3000/lib/handlebars.js:120:41)↵    at showLuckList (http://localhost:3000/lottery-start.js:89:29)↵    at Object.success (http://localhost:3000/lottery-start.js:147:7)↵    at i (http://localhost:3000/lib/jquery.min.js:2:27451)↵    at Object.fireWith [as resolveWith](http://localhost:3000/lib/jquery.min.js:2:28215)↵    at y (http://localhost:3000/lib/jquery.min.js:4:22592)↵    at XMLHttpRequest.c (http://localhost:3000/lib/jquery.min.js:4:26750)"**proto**: Error
    at Object.<anonymous> (http://localhost:3000/lib/handlebars.js:527:24)
    at **webpack_require** (http://localhost:3000/lib/handlebars.js:56:30)
    at Object.exports.**esModule (http://localhost:3000/lib/handlebars.js:266:19)
    at __webpack_require** (http://localhost:3000/lib/handlebars.js:56:30)
    at Object.exports.default.newObj (http://localhost:3000/lib/handlebars.js:173:24)
    at **webpack_require** (http://localhost:3000/lib/handlebars.js:56:30)
    at Object.exports.default.obj.**esModule.default (http://localhost:3000/lib/handlebars.js:89:27)
    at __webpack_require** (http://localhost:3000/lib/handlebars.js:56:30)
    at http://localhost:3000/lib/handlebars.js:76:18
    at http://localhost:3000/lib/handlebars.js:79:10compile @ handlebars.js:3234hb.compile @ handlebars.js:120showLuckList @ lottery-start.js:89(anonymous function) @ lottery-start.js:147i @ jquery.min.js:2fireWith @ jquery.min.js:2y @ jquery.min.js:4c @ jquery.min.js:4

**Comment by xiaoyangh** [comment]
![qq20161117-0](https://cloud.githubusercontent.com/assets/1456254/20375362/c8ec33e6-acb9-11e6-96cd-6c4ad21290b1.png)
不知道什么原因呢？有时候可以，有时候又不行

**Comment by huyinghuan** [comment]
查看页面里面 相关的template  模版有哪些， 根据你设置的抽奖人数  ，增加一些膜拜就好了，具体的id和人数的关系可以看下代码， 有
![image](https://cloud.githubusercontent.com/assets/3005433/20376883/a720fd6c-acc5-11e6-8722-f66405e75577.png)

![image](https://cloud.githubusercontent.com/assets/3005433/20378363/92519fa8-acd0-11e6-96ef-0a08cc994480.png)

**Comment by xiaoyangh** [comment]
好的，谢谢！我看了下你里面的代码，好像有lotteryListTemplate_900这个模板，应该是30个人吧，math.pow(30,2)=900，不过好像不是

**Comment by huyinghuan** [comment]
![image](https://cloud.githubusercontent.com/assets/3005433/20378623/40a26cc6-acd2-11e6-86de-3db05316dc0b.png)
