### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by urielQ** [huyinghuan/lottery-2016#3]
SyntaxError: Invalid regular expression: /^\api\lottery\(?:([^\/]+?))\/?$/: Unmatched ')'
    at new RegExp (<anonymous>:null:null)
    at pathtoRegexp (C:\Users\elfaz\Documents\GitHub\lottery-2016\node_modules\_path-to-regexp@0.1.7@path-to-regexp\index.js:128:10)
    at new Layer (C:\Users\elfaz\Documents\GitHub\lottery-2016\node_modules\_express@4.16.3@express\lib\router\layer.js:45:17)
    at Function.route (C:\Users\elfaz\Documents\GitHub\lottery-2016\node_modules\_express@4.16.3@express\lib\router\index.js:494:15)
    at new Router (C:\Users\elfaz\Documents\GitHub\lottery-2016\node_modules\_water-pit@0.0.4@water-pit\lib\router.js:16:14)
    at Waterpit.initRouter (C:\Users\elfaz\Documents\GitHub\lottery-2016\node_modules\_water-pit@0.0.4@water-pit\lib\index.js:25:22)
    at new Waterpit (C:\Users\elfaz\Documents\GitHub\lottery-2016\node_modules\_water-pit@0.0.4@water-pit\lib\index.js:16:12)
    at Object.<anonymous> (C:\Users\elfaz\Documents\GitHub\lottery-2016\app.coffee:12:9)
    at Object.<anonymous> (C:\Users\elfaz\Documents\GitHub\lottery-2016\app.coffee:1:1)
    at Module._compile (module.js:652:30)
    at loadFile (C:\Users\elfaz\Documents\GitHub\lottery-2016\node_modules\_coffee-script@1.12.7@coffee-script\lib\coffee-script\register.js:16:19)
    at Object.nodeDevHook [as .coffee] (C:\Users\elfaz\AppData\Roaming\npm\node_modules\node-dev\lib\hook.js:61:7)
    at Module.load (C:\Users\elfaz\Documents\GitHub\lottery-2016\node_modules\_coffee-script@1.12.7@coffee-script\lib\coffee-script\register.js:45:36)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\elfaz\AppData\Roaming\npm\node_modules\node-dev\lib\wrap.js:73:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

[ERROR] 11:06:35 SyntaxError
--- Update table award begin...
--- Update table employee begin...
--- Update table lottery begin...

**Comment by zhaoxiang2018** [comment]
我也出现这个问题了！！

**Comment by crazy2323** [comment]
linux环境下可以
